version: '3.9'

services:
  db:
    container_name: b2life-db
    image: postgres:15
    env_file:
      - backend/.env
    restart: always
    volumes:
      - b2data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend_network

  app:
    container_name: b2life-backend
    build: backend
    env_file:
      - backend/.env
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend_network

  adminer:
    container_name: database-monitoring
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db
    networks:
      - backend_network
  
  web:
    container_name: b2life-front
    build: frontend
    env_file: 
     - frontend/.env
    ports:
     - "3000:3000"
    depends_on:
     - app

volumes:
  b2data:

networks:
  backend_network: